name: Build and Publish VSIX

on:
    push:
        tags:
        - "v*"

permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
                node-version: '20'
        - run: npm install
        - run: npm install -g @vscode/vsce
        - run: npm run build
        - run: vsce package
        - uses: actions/upload-artifact@v4
          with:
            name: vsix
            path: '*.vsix'

    release:
      needs: build
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: vsix
            path: './'
        - name: create release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref_name }}
          run: |
            gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              'vscode-features-analyzer-0.0.2.vsix'
