name: Build and Publish VSIX

on:
    push:
        branches:
        - main


jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
                node-version: '20'
        - run: npm install
        - run: npm install -g @vscode/vsce
        - run: npm run build
        - run: vsce package
        - name: Upload vsix to release
          uses: AButler/upload-release-assets@v3.0
          with:
            files: '*.vsix'
            repo-token: ${{ secrets.GITHUB_TOKEN }}
        - uses: lannonbr/vsce-action@master
          if: github.event.release.prerelease == false
          with:
            args: "publish -p $VSCE_PAT"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}