name: Build and Publish VSIX

on:
    push:
        branches:
        - main
        tags:
        - "v*"

permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
                node-version: '20'
        - run: npm install
        - run: npm install -g @vscode/vsce
        - run: npm run build
        - run: vsce package
        - run: |
            FILE_NAME=$(ls *.vsix)
            echo "VSIX_FILE=$FILE_NAME" >> $GITHUB_ENV
        - uses: actions/upload-artifact@v4
          with:
            name: vsix
            path: '*.vsix'

    release:
      needs: build
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: vsix
            path: './'
        - run: ls -la
        - name: create release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref_name }}
            VSIX_FILE: ${{ env.VSIX_FILE }}
          run: |
            gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              "$VSIX_FILE"
